#!/bin/bash

echo "List of running vms: "
echo "============="
list=$(vboxmanage list runningvms | awk '{print $1}' | sed 's/"//g')
if [[ $list == "" ]]
then
 echo "There are no runnings vms";
 exit 0;
fi
no=0
total=0
for i in $list;
do no=$((no+1)); echo $no. $i; total=$((total+1));
done
echo "============="
read -p "Select vms to stop (vms name): " vms
if [[ ${vms} == ""  ]]
then
 echo "Please choose vms "
 exit 0
fi
false=0
for n in $list;
do 
 if [ $n != $vms ]; then 
    #echo $vms $n; 
    false=$((false+1)); 
    if [ $false == $total ]; then
      echo "There are vms name $vms"
      exit 0;
    fi;
 fi; 
done
echo "Stopping ${vms}...."
vboxmanage controlvm ${vms} poweroff 
echo "============="
